In [26]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import re
import os

In [27]:
customers = pd.read_csv("D:\Downloads Crome\customers.csv")
products = pd.read_csv("D:\Downloads Crome\products.csv")
orders = pd.read_csv("D:\Downloads Crome\orders.csv")
order_items = pd.read_csv("D:\Downloads Crome\order_items.csv")

In [28]:
customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Allison Hill,donaldgarcia@example.net,2026-04-07,REGULAR
1,C0002,Javier Johnson,jesseguzman@example.net,2024-03-08,REGULAR
2,C0003,Kimberly Robinson,lisa02@example.net,2024-11-09,VIP
3,C0004,Daniel Gallagher,daviscolin@example.com,2025-05-26,VIP
4,C0005,Monica Herrera,smiller@example.net,2025-06-11,REGULAR

In [29]:
products.head()

  product_id          product_name     category subcategory  cost_price
0      P0001       Monitor morning  Electronics     Monitor     1398.61
1      P0002       Keyboard action  Electronics    Keyboard     3284.20
2      P0003  Headphones recognize  Electronics  Headphones     4310.78
3      P0004          Monitor edge  Electronics     Monitor     3171.32
4      P0005          Monitor thus  Electronics     Monitor      275.91

In [30]:
orders.head()

  order_id customer_id           order_date     status region_code
0    O0001       C0125  2025-03-22 19:06:24    SHIPPED        WEST
1    O0002       C0138  2026-07-03 02:16:58  CANCELLED       SOUTH
2    O0003       C0223  2025-08-16 10:58:18  DELIVERED        WEST
3    O0004       C0185  2024-08-11 06:19:48    SHIPPED        WEST
4    O0005       C0101  2026-04-04 01:11:46    SHIPPED        EAST

In [31]:
order_items.head()

  item_id order_id product_id  quantity  unit_price  discount_percent
0  I00001    O0078      P0026         2     6791.04              1.11
1  I00002    O0065      P0367         1     3125.07              0.41
2  I00003    O0253      P0112         1     2459.20             15.58
3  I00004    O0238      P0357         4     5560.83             16.51
4  I00005    O0398      P0201         2      592.55             23.51

In [32]:
print(customers.shape)
print(products.shape)
print(orders.shape)
print(order_items.shape)

(500, 5)
(500, 5)
(500, 5)
(1000, 6)

In [33]:
print(customers.isnull().sum())
print(products.isnull().sum())
print(orders.isnull().sum())
print(order_items.isnull().sum())

customer_id          0
customer_name        0
email                0
registration_date    0
customer_type        0
dtype: int64
product_id      0
product_name    0
category        0
subcategory     0
cost_price      0
dtype: int64
order_id        0
customer_id    25
order_date      0
status          0
region_code     0
dtype: int64
item_id             0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
dtype: int64

In [34]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        500 non-null    str
 1   customer_name      500 non-null    str
 2   email              500 non-null    str
 3   registration_date  500 non-null    str
 4   customer_type      500 non-null    str
dtypes: str(5)
memory usage: 47.0 KB

In [35]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    str
 1   product_name  500 non-null    str
 2   category      500 non-null    str
 3   subcategory   500 non-null    str
 4   cost_price    500 non-null    float64
dtypes: float64(1), str(4)
memory usage: 35.2 KB

In [36]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     500 non-null    str
 1   customer_id  475 non-null    str
 2   order_date   500 non-null    str
 3   status       500 non-null    str
 4   region_code  500 non-null    str
dtypes: str(5)
memory usage: 39.8 KB

In [37]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           1000 non-null   str
 1   order_id          1000 non-null   str
 2   product_id        1000 non-null   str
 3   quantity          1000 non-null   int64
 4   unit_price        1000 non-null   float64
 5   discount_percent  1000 non-null   float64
dtypes: float64(2), int64(1), str(3)
memory usage: 62.6 KB

In [38]:
print("Customers :", customers.duplicated().sum())
print("Products :", products.duplicated().sum())
print("Orders :", orders.duplicated().sum())
print("Order Items :", order_items.duplicated().sum())

Customers : 0
Products : 0
Orders : 0
Order Items : 0

In [39]:
customers = customers.drop_duplicates()
products = products.drop_duplicates()
orders = orders.drop_duplicates()
order_items = order_items.drop_duplicates()

In [40]:
print("Customers :", customers.duplicated().sum())
print("Products :", products.duplicated().sum())
print("Orders :", orders.duplicated().sum())
print("Order Items :", order_items.duplicated().sum())

Customers : 0
Products : 0
Orders : 0
Order Items : 0

In [41]:
orders[orders["customer_id"].isnull()]

    order_id customer_id           order_date     status region_code
5      O0006         NaN  2025-02-01 12:12:03   RETURNED        WEST
47     O0048         NaN  2024-09-12 17:10:03  DELIVERED       SOUTH
78     O0079         NaN  2025-09-28 20:08:33     PLACED        WEST
103    O0104         NaN  2025-07-18 06:19:41     PLACED       SOUTH
111    O0112         NaN  2024-08-18 15:36:40    SHIPPED       SOUTH
160    O0161         NaN  2025-09-08 18:44:41  DELIVERED       SOUTH
162    O0163         NaN  2025-05-21 04:06:02    SHIPPED       NORTH
174    O0175         NaN  2026-04-08 16:21:32     PLACED        EAST
188    O0189         NaN  2025-11-08 03:05:24   RETURNED        WEST
193    O0194         NaN  2025-03-18 08:42:05  DELIVERED       SOUTH
208    O0209         NaN  2026-06-26 21:28:20    SHIPPED        WEST
209    O0210         NaN  2025-07-18 15:34:43  DELIVERED       SOUTH
210    O0211         NaN  2024-08-10 19:58:34  DELIVERED        EAST
211    O0212         NaN  2025-06-14 14:03:11  DELIVERED        EAST
219    O0220         NaN  2024-12-01 10:13:48  DELIVERED       SOUTH
224    O0225         NaN  08-06-2025 14:21:57   RETURNED       SOUTH
254    O0255         NaN  2025-03-19 18:16:50  DELIVERED       NORTH
274    O0275         NaN  2025-06-23 17:38:47     PLACED        WEST
293    O0294         NaN  2026-04-27 01:05:57   RETURNED        WEST
329    O0330         NaN  2024-11-10 13:55:39   RETURNED        WEST
386    O0387         NaN  2025-07-29 02:57:11  DELIVERED        WEST
416    O0417         NaN  2025-07-05 05:56:13     PLACED       NORTH
430    O0431         NaN  2025-05-02 16:40:33   RETURNED        EAST
471    O0472         NaN  2026-01-14 17:20:03   RETURNED       SOUTH
482    O0483         NaN  2024-09-30 11:41:44     PLACED       NORTH

In [42]:
orders["customer_id"] = orders["customer_id"].fillna("UNKNOWN")

In [43]:
orders.isnull().sum()

order_id       0
customer_id    0
order_date     0
status         0
region_code    0
dtype: int64

In [44]:
products["product_name"] = (
    products["product_name"]
    .str.strip()
    .str.title()
)

In [45]:
products.head()

  product_id          product_name     category subcategory  cost_price
0      P0001       Monitor Morning  Electronics     Monitor     1398.61
1      P0002       Keyboard Action  Electronics    Keyboard     3284.20
2      P0003  Headphones Recognize  Electronics  Headphones     4310.78
3      P0004          Monitor Edge  Electronics     Monitor     3171.32
4      P0005          Monitor Thus  Electronics     Monitor      275.91

In [46]:
print("Invalid Dates:", orders["order_date"].isnull().sum())

Invalid Dates: 0

In [47]:
import os
os.getcwd()

'C:\\Users\\SUBHA PRAYASH'

In [48]:
import os

project=r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI"

print(os.path.exists(project))
print(os.listdir(project))

True
['Data', 'Notebook', 'Outputs', 'Screenshots', 'SQL']

In [49]:
import os

project =r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI"

os.makedirs(project + "/Data/Raw", exist_ok=True)
os.makedirs(project + "/Data/Cleaned", exist_ok=True)
os.makedirs(project + "/SQL", exist_ok=True)
os.makedirs(project + "/Outputs", exist_ok=True)
os.makedirs(project + "/Screenshots", exist_ok=True)
os.makedirs(project + "/Notebook", exist_ok=True)

print("Project folders verified successfully!")

Project folders verified successfully!

In [50]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\SUBHA PRAYASH
['-1.14-windows.xml', '.anaconda', '.android', '.bash_history', '.conda', '.condarc', '.continuum', '.copilot', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.python_history', '.TurboVPN', '.vscode', '.vscode-shared', 'anaconda_projects', 'ansel', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'customers.csv', 'Data', 'Data cleaning.ipynb', 'Desktop', 'Documents', 'Downloads', 'ecommerce.db', 'Ecommerce_Project_FINAL.py', 'employees.csv', 'employees_parquet.zip', 'Favorites', 'Final_Ecommerce_Project.ipynb', 'hs_err_pid5600.log', 'html', 'Links', 'Local Settings', 'MOVIE', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{970ff344-5cd6-11f0-96a2-e3faaf0baeb4}.TxR.0.regtrans-ms', 'NTUSER.DAT{970ff344-5cd6-11f0-96a2-e3faaf0baeb4}.TxR.1.regtrans-ms', 'NTUSER.DAT{970ff344-5cd6-11f0-96a2-e3faaf0baeb4}.TxR.2.regtrans-ms', 'NTUSER.DAT{970ff344-5cd6-11f0-96a2-e3faaf0baeb4}.TxR.blf', 'NTUSER.DAT{970ff345-5cd6-11f0-96a2-e3faaf0baeb4}.TM.blf', 'NTUSER.DAT{970ff345-5cd6-11f0-96a2-e3faaf0baeb4}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{970ff345-5cd6-11f0-96a2-e3faaf0baeb4}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'orders.csv', 'order_items.csv', 'Outputs', 'Pictures', 'PrintHood', 'products.csv', 'project.ipynb', 'Recent', 'replay_pid5600.log', 'Saved Games', 'Searches', 'SendTo', 'Spark_Assignment_Dataset_8200_Rows.csv', 'Start Menu', 'Templates', 'Untitled.ipynb', 'untitled.txt', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Videos', 'Week8_Ecommerce_Project']

In [51]:
print(os.listdir(project+r"\Data"))

['Cleaned', 'Raw']

In [52]:
print(os.listdir(project+r"/Data/Raw"))

['customers.csv', 'orders.csv', 'order_items.csv', 'products.csv']

In [53]:
print(os.listdir(project+r"/Data/Cleaned"))

['cleaning_report.csv', 'customers_clean.csv', 'orders_clean.csv', 'order_items_clean.csv', 'products_clean.csv']

In [54]:
print(os.listdir(project+r"\Outputs"))

['cli_report.txt', 'cohort_retention.csv', 'customers_no_delivery.csv', 'customer_category_shift.csv', 'customer_cumulative_revenue.csv', 'customer_order_gaps.csv', 'customer_quartiles.csv', 'frequently_bought_together.csv', 'monthly_customer_segments.csv', 'monthly_orders.csv', 'products_more_returns.csv', 'product_ranking.csv', 'return_rate_by_category.csv', 'revenue_by_category.csv', 'running_revenue_by_region.csv', 'top_10_customers.csv', 'year_over_year_revenue.csv']

In [55]:
print(os.listdir(project+r"\SQL"))

['Aggregations.sql', 'Cohort_Analysis.sql', 'Schema.sql', 'Window_Functions.sql']

In [56]:
print(os.listdir(project+r"\Notebook"))

['Final_Ecommerce_Project.ipynb']

In [57]:
import os

print(os.listdir(r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\Week_8_Ecommerce_Project_CEI\Data\Raw"))

['customers.csv', 'orders.csv', 'order_items.csv', 'products.csv']

In [58]:
import pandas as pd

base = r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\Week_8_Ecommerce_Project_CEI\Data\Raw"

customers = pd.read_csv(base + r"\customers.csv")
products = pd.read_csv(base + r"\products.csv")
orders = pd.read_csv(base + r"\orders.csv")
order_items = pd.read_csv(base + r"\order_items.csv")

print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)

Customers: (500, 5)
Products: (500, 5)
Orders: (500, 5)
Order Items: (1000, 6)

In [59]:
orders[~orders["order_date"].astype(str).str.match(
    r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$",
    na=False
)]

    order_id customer_id           order_date     status region_code
12     O0013       C0282  19-04-2025 09:55:30  CANCELLED       SOUTH
43     O0044       C0488  04-06-2026 06:51:35    SHIPPED       SOUTH
46     O0047       C0290  29-09-2025 09:41:06    SHIPPED        EAST
82     O0083       C0289  23-01-2025 09:53:27    SHIPPED        WEST
88     O0089       C0354  15-03-2026 16:27:31  DELIVERED       SOUTH
110    O0111       C0261  08-02-2025 10:00:01     PLACED       SOUTH
112    O0113       C0440  31-10-2024 17:20:42  CANCELLED       SOUTH
117    O0118       C0234  21-11-2025 08:07:12    SHIPPED        EAST
124    O0125       C0048  16-05-2026 00:28:36    SHIPPED        WEST
136    O0137       C0090  30-11-2024 11:57:54  CANCELLED        WEST
140    O0141       C0039  15-02-2025 13:03:55     PLACED       SOUTH
145    O0146       C0077  26-04-2025 10:41:57   RETURNED       SOUTH
200    O0201       C0065  13-03-2025 21:57:44     PLACED        WEST
224    O0225         NaN  08-06-2025 14:21:57   RETURNED       SOUTH
226    O0227       C0263  13-02-2026 15:23:10     PLACED        WEST
258    O0259       C0422  05-03-2026 06:44:45  DELIVERED        WEST
279    O0280       C0456  19-08-2025 20:13:43    SHIPPED       SOUTH
304    O0305       C0114  27-02-2026 11:22:46  DELIVERED        EAST
335    O0336       C0080  20-12-2024 18:55:35  DELIVERED       NORTH
350    O0351       C0079  08-05-2025 01:04:39  DELIVERED       NORTH
354    O0355       C0274  22-02-2026 00:37:03   RETURNED       NORTH
355    O0356       C0300  25-01-2025 14:09:32     PLACED        EAST
371    O0372       C0087  04-05-2026 05:31:25    SHIPPED       SOUTH
377    O0378       C0324  27-11-2025 18:13:38   RETURNED        WEST
432    O0433       C0346  14-06-2025 16:43:52    SHIPPED       NORTH
438    O0439       C0295  11-06-2026 16:37:51    SHIPPED        WEST
456    O0457       C0277  12-09-2025 14:25:27  DELIVERED        WEST
458    O0459       C0005  11-06-2026 12:41:44    SHIPPED        WEST
485    O0486       C0088  15-04-2025 07:36:47  DELIVERED        EAST

In [60]:
orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

In [61]:
mask = orders["order_date"].isna()

orders.loc[mask, "order_date"] = pd.to_datetime(
    orders.loc[mask, "order_date"].astype(str),
    format="%d-%m-%Y %H:%M:%S",
    errors="coerce"
)

In [62]:
print("Invalid dates remaining:", orders["order_date"].isna().sum())

Invalid dates remaining: 29

In [122]:
import pandas as pd

orders = pd.read_csv(
   r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI\Data\Raw\orders.csv"
)

print(orders["order_date"].head())

0    2025-03-22 19:06:24
1    2026-07-03 02:16:58
2    2025-08-16 10:58:18
3    2024-08-11 06:19:48
4    2026-04-04 01:11:46
Name: order_date, dtype: str

In [123]:
wrong_dates = orders[
    ~orders["order_date"].astype(str).str.match(
        r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$",
        na=False
    )
]

print("Wrong-format dates:", len(wrong_dates))
wrong_dates[["order_id", "order_date"]]

Wrong-format dates: 29

    order_id           order_date
12     O0013  19-04-2025 09:55:30
43     O0044  04-06-2026 06:51:35
46     O0047  29-09-2025 09:41:06
82     O0083  23-01-2025 09:53:27
88     O0089  15-03-2026 16:27:31
110    O0111  08-02-2025 10:00:01
112    O0113  31-10-2024 17:20:42
117    O0118  21-11-2025 08:07:12
124    O0125  16-05-2026 00:28:36
136    O0137  30-11-2024 11:57:54
140    O0141  15-02-2025 13:03:55
145    O0146  26-04-2025 10:41:57
200    O0201  13-03-2025 21:57:44
224    O0225  08-06-2025 14:21:57
226    O0227  13-02-2026 15:23:10
258    O0259  05-03-2026 06:44:45
279    O0280  19-08-2025 20:13:43
304    O0305  27-02-2026 11:22:46
335    O0336  20-12-2024 18:55:35
350    O0351  08-05-2025 01:04:39
354    O0355  22-02-2026 00:37:03
355    O0356  25-01-2025 14:09:32
371    O0372  04-05-2026 05:31:25
377    O0378  27-11-2025 18:13:38
432    O0433  14-06-2025 16:43:52
438    O0439  11-06-2026 16:37:51
456    O0457  12-09-2025 14:25:27
458    O0459  11-06-2026 12:41:44
485    O0486  15-04-2025 07:36:47

In [124]:
orders["order_date_clean"] = pd.to_datetime(
    orders["order_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

mask = orders["order_date_clean"].isna()

orders.loc[mask, "order_date_clean"] = pd.to_datetime(
    orders.loc[mask, "order_date"],
    format="%d-%m-%Y %H:%M:%S",
    errors="coerce"
)

print("Invalid dates remaining:", orders["order_date_clean"].isna().sum())

Invalid dates remaining: 0

In [125]:
orders["order_date"] = orders["order_date_clean"]
orders.drop(columns=["order_date_clean"], inplace=True)

print("Date cleaning completed successfully!")

Date cleaning completed successfully!

In [126]:
orders.head()

  order_id customer_id          order_date     status region_code
0    O0001       C0125 2025-03-22 19:06:24    SHIPPED        WEST
1    O0002       C0138 2026-07-03 02:16:58  CANCELLED       SOUTH
2    O0003       C0223 2025-08-16 10:58:18  DELIVERED        WEST
3    O0004       C0185 2024-08-11 06:19:48    SHIPPED        WEST
4    O0005       C0101 2026-04-04 01:11:46    SHIPPED        EAST

In [127]:
products["product_name"] = (
    products["product_name"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [128]:
products[["product_id", "product_name"]].head(10)

  product_id          product_name
0      P0001       Monitor Morning
1      P0002       Keyboard Action
2      P0003  Headphones Recognize
3      P0004          Monitor Edge
4      P0005          Monitor Thus
5      P0006           Laptop Sure
6      P0007   Headphones Positive
7      P0008        Monitor Return
8      P0009        Laptop Company
9      P0010      Laptop Sometimes

In [129]:
import re

def validate_email(email):
    pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
    return bool(re.match(pattern, str(email)))

invalid_emails = customers[
    ~customers["email"].apply(validate_email)
]

print("Invalid emails:", len(invalid_emails))

Invalid emails: 5

In [130]:
invalid_emails[["customer_id", "email"]]

    customer_id                       email
67        C0068  stricklandfrankexample.com
151       C0152         george97example.net
173       C0174    lisawilkersonexample.org
462       C0463         iballardexample.com
497       C0498  atkinsoncrystalexample.net

In [131]:
invalid_order_items = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

print("Invalid order references:", len(invalid_order_items))

Invalid order references: 0

In [132]:
invalid_order_items

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [133]:
print("Negative quantities:", (order_items["quantity"] < 0).sum())

Negative quantities: 35

In [134]:
print("Discount > 100:", (order_items["discount_percent"] > 100).sum())
print("Quantity = 0:", (order_items["quantity"] == 0).sum())

Discount > 100: 0
Quantity = 0: 0

In [135]:
print("Missing customer IDs before:", orders["customer_id"].isna().sum())

orders["customer_id"] = orders["customer_id"].fillna("UNKNOWN")

print("Missing customer IDs after:", orders["customer_id"].isna().sum())

Missing customer IDs before: 25
Missing customer IDs after: 0

In [136]:
products["product_name"] = (
    products["product_name"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [137]:
import re

def validate_email(email):
    return bool(re.match(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",str(email)))

invalid_emails = customers[~customers["email"].apply(validate_email)]

print("Invalid emails:",len(invalid_emails))
invalid_emails[["customer_id","email"]]

Invalid emails: 5

    customer_id                       email
67        C0068  stricklandfrankexample.com
151       C0152         george97example.net
173       C0174    lisawilkersonexample.org
462       C0463         iballardexample.com
497       C0498  atkinsoncrystalexample.net

In [139]:
import os

clean_path = r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI\Data\Cleaned"

os.makedirs(clean_path,exist_ok=True)

customers.to_csv(clean_path+r"\customers_clean.csv",index=False)
products.to_csv(clean_path+r"\products_clean.csv",index=False)
orders.to_csv(clean_path+r"\orders_clean.csv",index=False)
order_items.to_csv(clean_path+r"\order_items_clean.csv",index=False)

print("✅ All cleaned CSV files saved successfully!")

✅ All cleaned CSV files saved successfully!

In [80]:
print(os.listdir(clean_path))

['cleaning_report.csv', 'customers_clean.csv', 'orders_clean.csv', 'order_items_clean.csv', 'products_clean.csv']

In [81]:
import pandas as pd

cleaning_report = pd.DataFrame({
    "issue": [
        "Missing customer IDs",
        "Invalid emails",
        "Invalid order references",
        "Negative quantities (returns)",
        "Discount > 100",
        "Quantity = 0"
    ],
    "count": [
        25,
        len(invalid_emails),
        len(invalid_order_items),
        int((order_items["quantity"] < 0).sum()),
        int((order_items["discount_percent"] > 100).sum()),
        int((order_items["quantity"] == 0).sum())
    ]
})

cleaning_report

                           issue  count
0           Missing customer IDs     25
1                 Invalid emails      5
2       Invalid order references      0
3  Negative quantities (returns)     35
4                 Discount > 100      0
5                   Quantity = 0      0

In [142]:
cleaning_report.to_csv(
    r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI\Data\Cleaned\cleaning_report.csv",
    index=False
)

print("✅ Cleaning report saved!")

✅ Cleaning report saved!

In [143]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)

print("\nMissing values:")
print("Customers:", customers.isnull().sum().sum())
print("Products:", products.isnull().sum().sum())
print("Orders:", orders.isnull().sum().sum())
print("Order Items:", order_items.isnull().sum().sum())

Customers: (500, 5)
Products: (500, 5)
Orders: (500, 5)
Order Items: (1000, 6)

Missing values:
Customers: 0
Products: 0
Orders: 0
Order Items: 0

In [144]:
print("Invalid dates:", orders["order_date"].isna().sum())
print("Invalid order references:", len(invalid_order_items))

Invalid dates: 0
Invalid order references: 0

In [145]:
import sqlite3

db_path = r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI\ecommerce.db"

conn = sqlite3.connect(db_path)

print("✅ SQLite database connected!")

✅ SQLite database connected!

In [146]:
cursor = conn.cursor()

cursor.executescript("""
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    email TEXT,
    registration_date TEXT,
    customer_type TEXT
);

CREATE TABLE products (
    product_id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT,
    subcategory TEXT,
    cost_price REAL
);

CREATE TABLE orders (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    order_date TEXT NOT NULL,
    status TEXT,
    region_code TEXT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    item_id TEXT PRIMARY KEY,
    order_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    quantity INTEGER,
    unit_price REAL,
    discount_percent REAL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);
""")

conn.commit()

print("✅ Tables created successfully!")

✅ Tables created successfully!

In [147]:
customers_db = customers.copy()

if "UNKNOWN" in orders["customer_id"].values and "UNKNOWN" not in customers_db["customer_id"].values:
    customers_db.loc[len(customers_db)] = [
        "UNKNOWN",
        "Unknown Customer",
        None,
        None,
        "UNKNOWN"
    ]

In [148]:
customers_db.to_sql("customers", conn, if_exists="append", index=False)
products.to_sql("products", conn, if_exists="append", index=False)
orders.to_sql("orders", conn, if_exists="append", index=False)
order_items.to_sql("order_items", conn, if_exists="append", index=False)

print("✅ All cleaned data loaded into SQLite!")

✅ All cleaned data loaded into SQLite!

In [149]:
for table in ["customers", "products", "orders", "order_items"]:
    count = pd.read_sql_query(
        f"SELECT COUNT(*) AS count FROM {table}",
        conn
    )
    print(table, ":", count.iloc[0]["count"])

customers : 501
products : 500
orders : 500
order_items : 1000

In [150]:
pd.read_sql_query("""
SELECT COUNT(*) AS invalid_references
FROM order_items oi
LEFT JOIN orders o
ON oi.order_id = o.order_id
WHERE o.order_id IS NULL
""", conn)

   invalid_references
0                   0

In [151]:
pd.read_sql_query("""
SELECT COUNT(*) AS invalid_product_references
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id
WHERE p.product_id IS NULL
""", conn)

   invalid_product_references
0                           0

In [152]:
query1 = """
SELECT
    p.category,
    ROUND(SUM(
        oi.quantity * oi.unit_price *
        (1 - oi.discount_percent / 100.0)
    ), 2) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""

result1 = pd.read_sql_query(query1, conn)
result1

      category  total_revenue
0         Home     2198729.65
1        Books     1974557.09
2  Electronics     1898734.53
3     Clothing     1850875.11

In [153]:
query2 = """
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(
        oi.quantity * oi.unit_price *
        (1 - oi.discount_percent / 100.0)
    ), 2) AS total_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_order_value DESC
LIMIT 10;
"""

result2 = pd.read_sql_query(query2, conn)
result2

  customer_id         customer_name  total_order_value
0     UNKNOWN      Unknown Customer          346447.88
1       C0494           Emily Hayes          131392.31
2       C0449         Lisa Reynolds          115581.21
3       C0380       Frank Daugherty           88981.18
4       C0361      Christine Parker           87968.17
5       C0053  Miss Patricia Gibson           87935.00
6       C0080          Pamela Lopez           79020.45
7       C0079        Heather Chavez           77718.34
8       C0290           Travis Cook           76861.77
9       C0072        Steven Stevens           76559.05

In [154]:
query3 = """
WITH max_date AS (
    SELECT MAX(date(order_date)) AS latest_date
    FROM orders
)
SELECT
    strftime('%Y-%m', order_date) AS month,
    COUNT(*) AS order_count
FROM orders, max_date
WHERE date(order_date) >= date(max_date.latest_date, '-11 months')
GROUP BY strftime('%Y-%m', order_date)
ORDER BY month;
"""

result3 = pd.read_sql_query(query3, conn)
result3

      month  order_count
0   2025-09           23
1   2025-10           18
2   2025-11           25
3   2025-12           22
4   2026-01           18
5   2026-02           17
6   2026-03           23
7   2026-04           21
8   2026-05           15
9   2026-06           18
10  2026-07           16
11  2026-08            4

In [155]:
query4 = """
SELECT
    c.customer_id,
    c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(
    CASE WHEN o.status = 'DELIVERED' THEN 1 ELSE 0 END
) = 0
ORDER BY c.customer_id;
"""

result4 = pd.read_sql_query(query4, conn)
result4

    customer_id      customer_name
0         C0003  Kimberly Robinson
1         C0005     Monica Herrera
2         C0008        Maria Lynch
3         C0016       James Martin
4         C0017      Sandra Parker
..          ...                ...
212       C0492      Robert Phelps
213       C0493    Craig Carpenter
214       C0495      Jeffrey Smith
215       C0497     Matthew Miller
216       C0498       Angela Jones

[217 rows x 2 columns]

In [156]:
query5 = """
SELECT
    p.product_id,
    p.product_name,
    SUM(CASE WHEN oi.quantity > 0 THEN oi.quantity ELSE 0 END) AS purchases,
    ABS(SUM(CASE WHEN oi.quantity < 0 THEN oi.quantity ELSE 0 END)) AS returns
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING returns > purchases
ORDER BY returns DESC;
"""

result5 = pd.read_sql_query(query5, conn)
result5

   product_id         product_name  purchases  returns
0       P0005         Monitor Thus          3        5
1       P0054  Headphones Property          0        5
2       P0159      Shirt Direction          0        5
3       P0179     Jeans Everything          3        4
4       P0110      Headphones Drug          1        3
5       P0235      Jacket Hospital          1        3
6       P0349         Mixer Return          2        3
7       P0112           Phone Talk          1        2
8       P0123          Phone Radio          0        2
9       P0142      T-Shirt Evening          1        2
10      P0472       Biography Rule          1        2
11      P0223         Jeans Player          0        1
12      P0370        Lamp Politics          0        1

In [157]:
query6 = """
SELECT
    p.category,
    ABS(SUM(
        CASE WHEN oi.quantity < 0 THEN oi.quantity ELSE 0 END
    )) AS returned_items,
    SUM(ABS(oi.quantity)) AS total_items,
    ROUND(
        100.0 * ABS(SUM(
            CASE WHEN oi.quantity < 0 THEN oi.quantity ELSE 0 END
        )) / NULLIF(SUM(ABS(oi.quantity)), 0),
        2
    ) AS return_rate_percent
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY return_rate_percent DESC;
"""

result6 = pd.read_sql_query(query6, conn)
result6

      category  returned_items  total_items  return_rate_percent
0  Electronics              26          766                 3.39
1     Clothing              25          740                 3.38
2         Home              25          822                 3.04
3        Books               8          704                 1.14

In [158]:
import os

output_path = r"C:\Users\SUBHA PRAYASH\Week8_Ecommerce_Project\output"
os.makedirs(output_path, exist_ok=True)

In [159]:
result1.to_csv(output_path + r"\revenue_by_category.csv", index=False)
result2.to_csv(output_path + r"\top_10_customers.csv", index=False)
result3.to_csv(output_path + r"\monthly_orders.csv", index=False)
result4.to_csv(output_path + r"\customers_no_delivery.csv", index=False)
result5.to_csv(output_path + r"\products_more_returns.csv", index=False)
result6.to_csv(output_path + r"\return_rate_by_category.csv", index=False)

print("✅ Basic SQL reports saved!")

✅ Basic SQL reports saved!

In [160]:
query7 = """
WITH daily_revenue AS (
    SELECT
        o.region_code,
        date(o.order_date) AS order_date,
        ROUND(SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ), 2) AS daily_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.region_code, date(o.order_date)
)
SELECT
    region_code,
    order_date,
    daily_revenue,
    ROUND(
        SUM(daily_revenue) OVER (
            PARTITION BY region_code
            ORDER BY order_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 2
    ) AS running_total
FROM daily_revenue
ORDER BY region_code, order_date;
"""

result7 = pd.read_sql_query(query7, conn)
result7.head(20)

   region_code  order_date  daily_revenue  running_total
0         EAST  2024-08-04         383.50         383.50
1         EAST  2024-08-12       13928.83       14312.33
2         EAST  2024-08-21       39732.97       54045.30
3         EAST  2024-08-28       15607.25       69652.55
4         EAST  2024-08-31        5842.57       75495.12
5         EAST  2024-09-09        6147.58       81642.70
6         EAST  2024-09-14       10277.26       91919.96
7         EAST  2024-09-17       16627.92      108547.88
8         EAST  2024-09-19        6505.52      115053.40
9         EAST  2024-10-01       32809.10      147862.50
10        EAST  2024-10-16       43436.06      191298.56
11        EAST  2024-10-23       23940.39      215238.95
12        EAST  2024-11-04       25234.25      240473.20
13        EAST  2024-11-06       31839.30      272312.50
14        EAST  2024-11-17        5431.33      277743.83
15        EAST  2024-11-18        7052.82      284796.65
16        EAST  2024-11-21       43594.28      328390.93
17        EAST  2024-11-25       37365.44      365756.37
18        EAST  2024-11-26       37402.69      403159.06
19        EAST  2024-12-04       22081.41      425240.47

In [161]:
result7.to_csv(
    output_path + r"\running_revenue_by_region.csv",
    index=False
)

In [162]:
query8 = """
WITH product_revenue AS (
    SELECT
        p.category,
        p.product_id,
        p.product_name,
        ROUND(SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ), 2) AS total_revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY
        p.category,
        p.product_id,
        p.product_name
)
SELECT
    category,
    product_name,
    total_revenue,
    DENSE_RANK() OVER (
        PARTITION BY category
        ORDER BY total_revenue DESC
    ) AS rank_in_category
FROM product_revenue
ORDER BY category, rank_in_category;
"""

result8 = pd.read_sql_query(query8, conn)
result8.head(20)

   category            product_name  total_revenue  rank_in_category
0     Books           Comics Summer       68213.51                 1
1     Books       Science Book Word       65075.09                 2
2     Books              Novel Push       50144.15                 3
3     Books           Biography Few       47535.09                 4
4     Books            Novel Happen       47283.89                 5
5     Books  Science Book Operation       40495.81                 6
6     Books             Comics Miss       40321.95                 7
7     Books             Novel Score       39419.51                 8
8     Books          Novel Continue       38559.49                 9
9     Books           Dictionary To       37913.95                10
10    Books             Novel Along       37770.47                11
11    Books    Novel Responsibility       37033.14                12
12    Books       Biography Evening       36685.88                13
13    Books            Comics Peace       35591.81                14
14    Books            Comics Paper       35224.91                15
15    Books          Dictionary Who       34035.57                16
16    Books             Comics Drug       32371.81                17
17    Books        Dictionary Level       31656.81                18
18    Books         Dictionary Step       31285.30                19
19    Books              Novel Each       31029.86                20

In [163]:
result8.to_csv(
    output_path + r"\product_ranking.csv",
    index=False
)

In [164]:
query9 = """
WITH customer_orders AS (
    SELECT
        customer_id,
        order_id,
        date(order_date) AS order_date,
        LAG(date(order_date)) OVER (
            PARTITION BY customer_id
            ORDER BY date(order_date)
        ) AS previous_order_date
    FROM orders
    WHERE customer_id != 'UNKNOWN'
),
order_gaps AS (
    SELECT
        customer_id,
        order_id,
        order_date,
        previous_order_date,
        CASE
            WHEN previous_order_date IS NOT NULL
            THEN julianday(order_date) - julianday(previous_order_date)
        END AS days_gap
    FROM customer_orders
),
avg_gaps AS (
    SELECT
        customer_id,
        AVG(days_gap) AS average_gap
    FROM order_gaps
    WHERE days_gap IS NOT NULL
    GROUP BY customer_id
)
SELECT
    g.customer_id,
    g.order_date,
    g.previous_order_date,
    ROUND(g.days_gap, 2) AS days_gap,
    CASE
        WHEN a.average_gap > 30 THEN 'At Risk'
        ELSE 'Active'
    END AS customer_status
FROM order_gaps g
JOIN avg_gaps a
    ON g.customer_id = a.customer_id
ORDER BY g.customer_id, g.order_date;
"""

result9 = pd.read_sql_query(query9, conn)
result9.head(20)

   customer_id  order_date previous_order_date  days_gap customer_status
0        C0007  2025-04-12                 NaN       NaN         At Risk
1        C0007  2026-04-16          2025-04-12     369.0         At Risk
2        C0023  2024-10-21                 NaN       NaN         At Risk
3        C0023  2024-12-28          2024-10-21      68.0         At Risk
4        C0023  2026-02-02          2024-12-28     401.0         At Risk
5        C0036  2025-08-27                 NaN       NaN          Active
6        C0036  2025-09-02          2025-08-27       6.0          Active
7        C0036  2025-09-19          2025-09-02      17.0          Active
8        C0039  2025-02-15                 NaN       NaN         At Risk
9        C0039  2025-06-19          2025-02-15     124.0         At Risk
10       C0041  2025-03-14                 NaN       NaN          Active
11       C0041  2025-03-22          2025-03-14       8.0          Active
12       C0041  2025-04-28          2025-03-22      37.0          Active
13       C0047  2025-09-25                 NaN       NaN         At Risk
14       C0047  2026-01-24          2025-09-25     121.0         At Risk
15       C0048  2025-07-15                 NaN       NaN         At Risk
16       C0048  2026-05-16          2025-07-15     305.0         At Risk
17       C0052  2025-07-06                 NaN       NaN         At Risk
18       C0052  2026-03-24          2025-07-06     261.0         At Risk
19       C0052  2026-06-22          2026-03-24      90.0         At Risk

In [165]:
result9.to_csv(
    output_path + r"\customer_order_gaps.csv",
    index=False
)

In [166]:
query10 = """
WITH monthly_customer_revenue AS (
    SELECT
        o.customer_id,
        strftime('%Y-%m', o.order_date) AS month,
        SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.customer_id != 'UNKNOWN'
    GROUP BY o.customer_id, strftime('%Y-%m', o.order_date)
),
customer_categories AS (
    SELECT
        customer_id,
        month,
        revenue,
        CASE
            WHEN revenue > 10000 THEN 'High'
            WHEN revenue >= 5000 THEN 'Medium'
            ELSE 'Low'
        END AS revenue_category
    FROM monthly_customer_revenue
)
SELECT
    month,
    revenue_category,
    COUNT(*) AS customer_count
FROM customer_categories
GROUP BY month, revenue_category
ORDER BY month, revenue_category;
"""

result10 = pd.read_sql_query(query10, conn)
result10

      month revenue_category  customer_count
0   2024-08             High              12
1   2024-08              Low               2
2   2024-08           Medium               1
3   2024-09             High              11
4   2024-09              Low               1
..      ...              ...             ...
65  2026-07             High              12
66  2026-07              Low               1
67  2026-08             High               2
68  2026-08              Low               1
69  2026-08           Medium               1

[70 rows x 3 columns]

In [167]:
result10.to_csv(
    output_path + r"\monthly_customer_segments.csv",
    index=False
)

In [168]:
query11 = """
WITH customer_value AS (
    SELECT
        o.customer_id,
        ROUND(SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ), 2) AS total_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.customer_id != 'UNKNOWN'
    GROUP BY o.customer_id
),
quartiles AS (
    SELECT
        customer_id,
        total_value,
        NTILE(4) OVER (
            ORDER BY total_value DESC
        ) AS quartile
    FROM customer_value
)
SELECT
    customer_id,
    total_value,
    quartile,
    CASE quartile
        WHEN 1 THEN 'Platinum'
        WHEN 2 THEN 'Gold'
        WHEN 3 THEN 'Silver'
        WHEN 4 THEN 'Bronze'
    END AS quartile_label
FROM quartiles
ORDER BY quartile, total_value DESC;
"""

result11 = pd.read_sql_query(query11, conn)
result11

    customer_id  total_value  quartile quartile_label
0         C0494    131392.31         1       Platinum
1         C0449    115581.21         1       Platinum
2         C0380     88981.18         1       Platinum
3         C0361     87968.17         1       Platinum
4         C0053     87935.00         1       Platinum
..          ...          ...       ...            ...
277       C0497     -6236.37         4         Bronze
278       C0424     -7813.37         4         Bronze
279       C0281    -12680.66         4         Bronze
280       C0167    -12800.11         4         Bronze
281       C0214    -14381.24         4         Bronze

[282 rows x 4 columns]

In [169]:
result11.to_csv(
    output_path + r"\customer_quartiles.csv",
    index=False
)

In [170]:
query12 = """
WITH monthly_revenue AS (
    SELECT
        strftime('%Y', o.order_date) AS year,
        strftime('%m', o.order_date) AS month,
        SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        strftime('%Y', o.order_date),
        strftime('%m', o.order_date)
),
yoy AS (
    SELECT
        year,
        month,
        ROUND(revenue, 2) AS revenue,
        LAG(revenue, 12) OVER (
            ORDER BY year, month
        ) AS prev_year_revenue
    FROM monthly_revenue
)
SELECT
    year,
    month,
    revenue,
    ROUND(prev_year_revenue, 2) AS prev_year_revenue,
    CASE
        WHEN prev_year_revenue IS NULL OR prev_year_revenue = 0
        THEN NULL
        ELSE ROUND(
            100.0 * (revenue - prev_year_revenue)
            / prev_year_revenue,
            2
        )
    END AS yoy_growth_percent
FROM yoy
ORDER BY year, month;
"""

result12 = pd.read_sql_query(query12, conn)
result12

    year month    revenue  prev_year_revenue  yoy_growth_percent
0   2024    08  382497.56                NaN                 NaN
1   2024    09  359069.31                NaN                 NaN
2   2024    10  340892.79                NaN                 NaN
3   2024    11  376858.06                NaN                 NaN
4   2024    12  520827.71                NaN                 NaN
5   2025    01  383252.71                NaN                 NaN
6   2025    02  345008.64                NaN                 NaN
7   2025    03  250765.76                NaN                 NaN
8   2025    04  318561.67                NaN                 NaN
9   2025    05  271321.31                NaN                 NaN
10  2025    06  188760.69                NaN                 NaN
11  2025    07  360553.79                NaN                 NaN
12  2025    08  233237.76          382497.56              -39.02
13  2025    09  386371.30          359069.31                7.60
14  2025    10  251738.54          340892.79              -26.15
15  2025    11  535462.20          376858.06               42.09
16  2025    12  361647.01          520827.71              -30.56
17  2026    01  198608.47          383252.71              -48.18
18  2026    02  215075.80          345008.64              -37.66
19  2026    03  340885.64          250765.76               35.94
20  2026    04  265762.20          318561.67              -16.57
21  2026    05  291005.17          271321.31                7.25
22  2026    06  402459.11          188760.69              113.21
23  2026    07  285759.88          360553.79              -20.74
24  2026    08   56513.31          233237.76              -75.77

In [171]:
result12.to_csv(
    output_path + r"\year_over_year_revenue.csv",
    index=False
)

In [172]:
query13 = """
WITH customer_categories AS (
    SELECT
        o.customer_id,
        p.category,
        o.order_date,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY o.order_date
        ) AS first_rank,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY o.order_date DESC
        ) AS last_rank
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.customer_id != 'UNKNOWN'
),
first_last AS (
    SELECT
        customer_id,
        MAX(CASE WHEN first_rank = 1 THEN category END) AS first_category,
        MAX(CASE WHEN last_rank = 1 THEN category END) AS recent_category
    FROM customer_categories
    GROUP BY customer_id
)
SELECT
    customer_id,
    first_category,
    recent_category,
    CASE
        WHEN first_category != recent_category THEN 'Yes'
        ELSE 'No'
    END AS category_shift
FROM first_last
ORDER BY customer_id;
"""

result13 = pd.read_sql_query(query13, conn)
result13.head(20)

   customer_id first_category recent_category category_shift
0        C0003          Books           Books             No
1        C0004       Clothing        Clothing             No
2        C0005           Home            Home             No
3        C0007           Home     Electronics            Yes
4        C0008           Home            Home             No
5        C0013          Books           Books             No
6        C0016          Books           Books             No
7        C0017    Electronics     Electronics             No
8        C0019          Books           Books             No
9        C0020          Books           Books             No
10       C0021    Electronics     Electronics             No
11       C0023       Clothing     Electronics            Yes
12       C0024           Home            Home             No
13       C0025       Clothing        Clothing             No
14       C0028    Electronics     Electronics             No
15       C0029       Clothing        Clothing             No
16       C0036          Books     Electronics            Yes
17       C0037       Clothing        Clothing             No
18       C0038       Clothing        Clothing             No
19       C0039           Home            Home             No

In [173]:
query14 = """
WITH customer_revenue AS (
    SELECT
        o.customer_id,
        SUM(
            oi.quantity * oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.customer_id != 'UNKNOWN'
    GROUP BY o.customer_id
),
ranked AS (
    SELECT
        customer_id,
        ROUND(revenue, 2) AS revenue,
        SUM(revenue) OVER (
            ORDER BY revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM customer_revenue
)
SELECT
    customer_id,
    revenue,
    ROUND(cumulative_revenue, 2) AS cumulative_revenue,
    ROUND(
        100.0 * cumulative_revenue / total_revenue,
        2
    ) AS cumulative_percent
FROM ranked
ORDER BY revenue DESC;
"""

result14 = pd.read_sql_query(query14, conn)
result14.head(20)

   customer_id    revenue  cumulative_revenue  cumulative_percent
0        C0494  131392.31           131392.31                1.73
1        C0449  115581.21           246973.52                3.26
2        C0380   88981.18           335954.70                4.43
3        C0361   87968.17           423922.87                5.60
4        C0053   87935.00           511857.87                6.76
5        C0080   79020.45           590878.32                7.80
6        C0079   77718.34           668596.65                8.82
7        C0290   76861.77           745458.42                9.84
8        C0072   76559.05           822017.47               10.85
9        C0206   76060.23           898077.70               11.85
10       C0333   69991.28           968068.98               12.78
11       C0402   69567.18          1037636.16               13.70
12       C0204   69172.78          1106808.94               14.61
13       C0201   68936.49          1175745.43               15.52
14       C0108   67504.02          1243249.45               16.41
15       C0488   65799.21          1309048.66               17.28
16       C0310   65748.80          1374797.46               18.15
17       C0304   63965.21          1438762.67               18.99
18       C0413   62965.87          1501728.53               19.82
19       C0299   62722.15          1564450.68               20.65

In [174]:
result13.to_csv(
    output_path + r"\customer_category_shift.csv",
    index=False
)

result14.to_csv(
    output_path + r"\customer_cumulative_revenue.csv",
    index=False
)

print("✅ Advanced SQL reports saved!")

✅ Advanced SQL reports saved!

In [175]:
query15 = """
WITH customer_cohort AS (
    SELECT
        customer_id,
        strftime('%Y-%m', registration_date) AS cohort_month
    FROM customers
    WHERE customer_id != 'UNKNOWN'
),
customer_orders AS (
    SELECT DISTINCT
        o.customer_id,
        strftime('%Y-%m', o.order_date) AS order_month
    FROM orders o
    WHERE o.customer_id != 'UNKNOWN'
),
cohort_activity AS (
    SELECT
        c.customer_id,
        c.cohort_month,
        o.order_month,
        (
            (CAST(strftime('%Y', o.order_month || '-01') AS INTEGER) -
             CAST(strftime('%Y', c.cohort_month || '-01') AS INTEGER)) * 12
            +
            (CAST(strftime('%m', o.order_month || '-01') AS INTEGER) -
             CAST(strftime('%m', c.cohort_month || '-01') AS INTEGER))
        ) AS month_number
    FROM customer_cohort c
    JOIN customer_orders o
        ON c.customer_id = o.customer_id
),
cohort_size AS (
    SELECT
        cohort_month,
        COUNT(DISTINCT customer_id) AS cohort_customers
    FROM customer_cohort
    GROUP BY cohort_month
),
retention AS (
    SELECT
        ca.cohort_month,
        ca.month_number,
        COUNT(DISTINCT ca.customer_id) AS customers_ordered
    FROM cohort_activity ca
    WHERE ca.month_number BETWEEN 0 AND 3
    GROUP BY ca.cohort_month, ca.month_number
)
SELECT
    r.cohort_month,
    r.month_number,
    r.customers_ordered,
    cs.cohort_customers,
    ROUND(
        100.0 * r.customers_ordered / cs.cohort_customers,
        2
    ) AS retention_rate
FROM retention r
JOIN cohort_size cs
    ON r.cohort_month = cs.cohort_month
ORDER BY r.cohort_month, r.month_number;
"""

result15 = pd.read_sql_query(query15, conn)
result15

,cohort_month,month_number,customers_ordered,cohort_customers,retention_rate
0,2024-05,3,1,16,6.25
1,2024-07,1,1,17,5.88
2,2024-07,2,1,17,5.88
3,2024-07,3,1,17,5.88
4,2024-08,0,1,18,5.56
5,2024-08,1,1,18,5.56
6,2024-08,2,1,18,5.56
7,2024-09,0,1,11,9.09
8,2024-09,1,1,11,9.09
9,2024-09,2,1,11,9.09
10,2024-09,3,1,11,9.09
11,2024-10,0,1,13,7.69
12,2024-11,0,1,9,11.11
13,2024-12,0,2,16,12.50
14,2024-12,2,1,16,6.25
15,2025-01,1,1,15,6.67
16,2025-02,0,3,16,18.75
17,2025-02,1,1,16,6.25
18,2025-03,0,2,13,15.38
19,2025-03,1,1,13,7.69
20,2025-03,3,2,13,15.38
21,2025-04,3,1,15,6.67
22,2025-05,3,2,19,10.53
23,2025-06,0,2,17,11.76
24,2025-06,1,2,17,11.76
25,2025-07,2,2,9,22.22
26,2025-07,3,1,9,11.11
27,2025-08,3,1,13,7.69
28,2025-09,1,1,12,8.33
29,2025-09,3,1,12,8.33
30,2025-10,0,1,10,10.00
31,2025-11,1,2,12,16.67
32,2025-11,2,1,12,8.33
33,2025-12,0,2,15,13.33
34,2025-12,2,1,15,6.67
35,2025-12,3,1,15,6.67
36,2026-03,2,1,11,9.09
37,2026-03,3,1,11,9.09
38,2026-04,1,1,7,14.29
39,2026-06,1,2,17,11.76
40,2026-06,2,1,17,5.88

In [176]:
result15.to_csv(
    output_path + r"\cohort_retention.csv",
    index=False
)

print("✅ Cohort report saved!")

✅ Cohort report saved!

In [177]:
query16 = """
SELECT
    p1.product_name AS product_a,
    p2.product_name AS product_b,
    COUNT(DISTINCT oi1.order_id) AS times_bought_together
FROM order_items oi1
JOIN order_items oi2
    ON oi1.order_id = oi2.order_id
    AND oi1.product_id < oi2.product_id
JOIN products p1
    ON oi1.product_id = p1.product_id
JOIN products p2
    ON oi2.product_id = p2.product_id
GROUP BY
    oi1.product_id,
    oi2.product_id,
    p1.product_name,
    p2.product_name
ORDER BY times_bought_together DESC;
"""

result16 = pd.read_sql_query(query16, conn)
result16.head(20)

               product_a         product_b  times_bought_together
0        Laptop National       Jacket Then                      2
1           Keyboard Off        Sofa Other                      2
2        Keyboard Action  Keyboard Country                      1
3   Headphones Recognize   Headphones Over                      1
4   Headphones Recognize       Jacket Care                      1
5   Headphones Recognize       Shoes After                      1
6   Headphones Recognize       Jacket Then                      1
7   Headphones Recognize      Shirt Writer                      1
8   Headphones Recognize    Sofa Necessary                      1
9   Headphones Recognize        Table Both                      1
10  Headphones Recognize       Lamp Summer                      1
11  Headphones Recognize     Comics Summer                      1
12          Monitor Thus      Monitor Sign                      1
13          Monitor Thus     Comics Summer                      1
14           Laptop Sure         Chair How                      1
15           Laptop Sure     Lamp Hospital                      1
16   Headphones Positive       Sofa Accept                      1
17        Monitor Return    Table Security                      1
18        Monitor Return     Mixer Country                      1
19        Monitor Return     Novel Defense                      1

In [178]:
result16.to_csv(
    output_path + r"\frequently_bought_together.csv",
    index=False
)

print("✅ Product pair report saved!")

✅ Product pair report saved!

In [179]:
import os

print("\nOutput files:\n")

for file in os.listdir(output_path):
    print("✓", file)

Output files:

✓ cli_report.txt
✓ cohort_retention.csv
✓ customers_no_delivery.csv
✓ customer_category_shift.csv
✓ customer_cumulative_revenue.csv
✓ customer_order_gaps.csv
✓ customer_quartiles.csv
✓ frequently_bought_together.csv
✓ monthly_customer_segments.csv
✓ monthly_orders.csv
✓ products_more_returns.csv
✓ product_ranking.csv
✓ return_rate_by_category.csv
✓ revenue_by_category.csv
✓ running_revenue_by_region.csv
✓ top_10_customers.csv
✓ year_over_year_revenue.csv

In [180]:
from datetime import datetime,timedelta
import calendar
import sqlite3
import pandas as pd

def generate_report(report_type,start_date,end_date):

    start=datetime.strptime(start_date,"%Y-%m-%d")
    end=datetime.strptime(end_date,"%Y-%m-%d")

    days=(end-start).days+1

    if report_type=="daily":
        prev_end=start-timedelta(days=1)
        prev_start=prev_end

    elif report_type=="weekly":
        prev_end=start-timedelta(days=1)
        prev_start=prev_end-timedelta(days=days-1)

    elif report_type=="monthly":
        prev_end=start-timedelta(days=1)
        prev_start=prev_end-timedelta(days=days-1)

    else:
        print("Invalid report type. Use daily, weekly or monthly.")
        return

    conn=sqlite3.connect(
       r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI\ecommerce.db"
    )

    summary_query="""
    SELECT
        COUNT(DISTINCT o.order_id) AS total_orders,
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2) AS revenue,
        COUNT(DISTINCT o.customer_id) AS unique_customers
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    """

    current=pd.read_sql_query(
        summary_query,
        conn,
        params=[start_date,end_date]
    )

    previous=pd.read_sql_query(
        summary_query,
        conn,
        params=[
            prev_start.strftime("%Y-%m-%d"),
            prev_end.strftime("%Y-%m-%d")
        ]
    )

    product_query="""
    SELECT
        p.product_name,
        SUM(oi.quantity) AS quantity_sold,
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    JOIN products p
        ON oi.product_id=p.product_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    GROUP BY p.product_id,p.product_name
    ORDER BY revenue DESC
    LIMIT 3
    """

    top_products=pd.read_sql_query(
        product_query,
        conn,
        params=[start_date,end_date]
    )

    conn.close()

    current_revenue=current.loc[0,"revenue"] or 0
    previous_revenue=previous.loc[0,"revenue"] or 0

    if previous_revenue!=0:
        revenue_change=(
            (current_revenue-previous_revenue)
            /previous_revenue
        )*100
    else:
        revenue_change=None

    print("\n========== E-COMMERCE REPORT ==========")
    print("Report Type:",report_type)
    print("Current Period:",start_date,"to",end_date)
    print(
        "Previous Period:",
        prev_start.strftime("%Y-%m-%d"),
        "to",
        prev_end.strftime("%Y-%m-%d")
    )

    print("\nCurrent Period:")
    print(current.to_string(index=False))

    print("\nPrevious Period:")
    print(previous.to_string(index=False))

    print("\nRevenue Change:",
          "N/A" if revenue_change is None
          else f"{revenue_change:.2f}%")

    print("\nTop 3 Products:")
    print(top_products.to_string(index=False))

    return current,previous,top_products

In [181]:
generate_report(
    "monthly",
    "2025-01-01",
    "2025-01-31"
)

========== E-COMMERCE REPORT ==========
Report Type: monthly
Current Period: 2025-01-01 to 2025-01-31
Previous Period: 2024-12-01 to 2024-12-31

Current Period:
 total_orders   revenue  unique_customers
           18 383252.71                18

Previous Period:
 total_orders   revenue  unique_customers
           25 520827.71                25

Revenue Change: -26.41%

Top 3 Products:
product_name  quantity_sold  revenue
 Novel Score              5 29920.23
  Novel Huge              5 25860.00
Monitor Sign              5 25552.62

(   total_orders    revenue  unique_customers
 0            18  383252.71                18,
    total_orders    revenue  unique_customers
 0            25  520827.71                25,
    product_name  quantity_sold   revenue
 0   Novel Score              5  29920.23
 1    Novel Huge              5  25860.00
 2  Monitor Sign              5  25552.62)

In [182]:
generate_report(
    "weekly",
    "2025-01-06",
    "2025-01-12"
)

========== E-COMMERCE REPORT ==========
Report Type: weekly
Current Period: 2025-01-06 to 2025-01-12
Previous Period: 2024-12-30 to 2025-01-05

Current Period:
 total_orders  revenue  unique_customers
            1 18843.21                 1

Previous Period:
 total_orders   revenue  unique_customers
            4 108712.21                 4

Revenue Change: -82.67%

Top 3 Products:
    product_name  quantity_sold  revenue
    Monitor Sign              5 25552.62
Biography Author              1  1417.46
  Jacket Soldier              1   955.26

(   total_orders   revenue  unique_customers
 0             1  18843.21                 1,
    total_orders    revenue  unique_customers
 0             4  108712.21                 4,
        product_name  quantity_sold   revenue
 0      Monitor Sign              5  25552.62
 1  Biography Author              1   1417.46
 2    Jacket Soldier              1    955.26)

In [183]:
generate_report(
    "daily",
    "2025-01-10",
    "2025-01-10"
)

========== E-COMMERCE REPORT ==========
Report Type: daily
Current Period: 2025-01-10 to 2025-01-10
Previous Period: 2025-01-09 to 2025-01-09

Current Period:
 total_orders revenue  unique_customers
            0    None                 0

Previous Period:
 total_orders revenue  unique_customers
            0    None                 0

Revenue Change: N/A

Top 3 Products:
Empty DataFrame
Columns: [product_name, quantity_sold, revenue]
Index: []

(   total_orders revenue  unique_customers
 0             0    None                 0,
    total_orders revenue  unique_customers
 0             0    None                 0,
 Empty DataFrame
 Columns: [product_name, quantity_sold, revenue]
 Index: [])

In [184]:
import sqlite3
import pandas as pd
from datetime import datetime,timedelta

DB=r"C:\Users\SUBHA PRAYASH\Week8_Ecommerce_Project\ecommerce.db"
OUTPUT=r"C:\Users\SUBHA PRAYASH\Week8_Ecommerce_Project\output"

def get_report(report_type,start_date,end_date):
    report_type=report_type.lower().strip()

    try:
        start=datetime.strptime(start_date,"%Y-%m-%d")
        end=datetime.strptime(end_date,"%Y-%m-%d")
    except ValueError:
        print("Invalid date. Use YYYY-MM-DD.")
        return

    if end<start:
        print("End date cannot be before start date.")
        return

    days=(end-start).days+1

    if report_type=="daily":
        prev_end=start-timedelta(days=1)
        prev_start=prev_end
    elif report_type in ["weekly","monthly"]:
        prev_end=start-timedelta(days=1)
        prev_start=prev_end-timedelta(days=days-1)
    else:
        print("Invalid report type. Use daily, weekly or monthly.")
        return

    conn=sqlite3.connect(DB)

    query="""
    SELECT
        COUNT(DISTINCT o.order_id),
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2),
        COUNT(DISTINCT o.customer_id)
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    """

    current=conn.execute(
        query,
        (start_date,end_date)
    ).fetchone()

    previous=conn.execute(
        query,
        (
            prev_start.strftime("%Y-%m-%d"),
            prev_end.strftime("%Y-%m-%d")
        )
    ).fetchone()

    product_query="""
    SELECT
        p.product_name,
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    JOIN products p
        ON oi.product_id=p.product_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    GROUP BY p.product_id,p.product_name
    ORDER BY revenue DESC
    LIMIT 3
    """

    products=conn.execute(
        product_query,
        (start_date,end_date)
    ).fetchall()

    conn.close()

    orders=current[0] or 0
    revenue=current[1] or 0
    customers=current[2] or 0
    previous_revenue=previous[1] or 0

    if previous_revenue!=0:
        change=(revenue-previous_revenue)/previous_revenue*100
    else:
        change=None

    print("\n========== E-COMMERCE REPORT ==========")
    print("Report Type:",report_type)
    print("Date Range:",start_date,"to",end_date)
    print("Total Orders:",orders)
    print("Revenue:",f"₹{revenue:,.2f}")
    print("Unique Customers:",customers)

    if change is None:
        print("Revenue Change:N/A")
    else:
        print("Revenue Change:",f"{change:.2f}%")

    print("\nTop 3 Products:")

    for i,(name,product_revenue) in enumerate(products,1):
        print(
            f"{i}. {name} - ₹{product_revenue:,.2f}"
        )

    report_file=OUTPUT+r"\cli_report.txt"

    with open(report_file,"w",encoding="utf-8") as f:
        f.write("========== E-COMMERCE REPORT ==========\n")
        f.write(f"Report Type: {report_type}\n")
        f.write(f"Date Range: {start_date} to {end_date}\n")
        f.write(f"Total Orders: {orders}\n")
        f.write(f"Revenue: ₹{revenue:,.2f}\n")
        f.write(f"Unique Customers: {customers}\n")

        if change is None:
            f.write("Revenue Change: N/A\n")
        else:
            f.write(f"Revenue Change: {change:.2f}%\n")

        f.write("\nTop 3 Products:\n")

        for i,(name,product_revenue) in enumerate(products,1):
            f.write(
                f"{i}. {name} - ₹{product_revenue:,.2f}\n"
            )

    print("\n✅ Report saved successfully.")
    print("Location:",report_file)

def test_invalid_order_id():
    conn=sqlite3.connect(DB)

    result=pd.read_sql_query("""
    SELECT COUNT(*) AS invalid_orders
    FROM order_items oi
    LEFT JOIN orders o
        ON oi.order_id=o.order_id
    WHERE o.order_id IS NULL
    """,conn)

    conn.close()

    print(
        "Invalid Order ID Test:",
        result.iloc[0,0]
    )

def test_discount():
    conn=sqlite3.connect(DB)

    result=pd.read_sql_query("""
    SELECT COUNT(*) AS invalid_discount
    FROM order_items
    WHERE discount_percent>100
    """,conn)

    conn.close()

    print(
        "Discount > 100 Test:",
        result.iloc[0,0]
    )

def test_zero_quantity():
    conn=sqlite3.connect(DB)

    result=pd.read_sql_query("""
    SELECT COUNT(*) AS zero_quantity
    FROM order_items
    WHERE quantity=0
    """,conn)

    conn.close()

    print(
        "Quantity = 0 Test:",
        result.iloc[0,0]
    )

def test_future_dates():
    conn=sqlite3.connect(DB)

    result=pd.read_sql_query("""
    SELECT COUNT(*) AS future_orders
    FROM orders
    WHERE date(order_date)>date('now')
    """,conn)

    conn.close()

    print(
        "Future Date Test:",
        result.iloc[0,0]
    )

if __name__=="__main__":

    report_type=input(
        "Enter report type (daily/weekly/monthly): "
    ).lower().strip()

    start_date=input(
        "Enter start date (YYYY-MM-DD): "
    ).strip()

    end_date=input(
        "Enter end date (YYYY-MM-DD): "
    ).strip()

    get_report(
        report_type,
        start_date,
        end_date
    )

    print("\n========== EDGE CASE TESTS ==========")

    test_invalid_order_id()
    test_discount()
    test_zero_quantity()
    test_future_dates()

Enter report type (daily/weekly/monthly):  monthly
Enter start date (YYYY-MM-DD):  2025-01-01
Enter end date (YYYY-MM-DD):  2025-01-31

========== E-COMMERCE REPORT ==========
Report Type: monthly
Date Range: 2025-01-01 to 2025-01-31
Total Orders: 18
Revenue: ₹383,252.71
Unique Customers: 18
Revenue Change: -26.41%

Top 3 Products:
1. Novel Score - ₹29,920.23
2. Novel Huge - ₹25,860.00
3. Monitor Sign - ₹25,552.62

✅ Report saved successfully.
Location: C:\Users\SUBHA PRAYASH\Week8_Ecommerce_Project\output\cli_report.txt

========== EDGE CASE TESTS ==========
Invalid Order ID Test: 0
Discount > 100 Test: 0
Quantity = 0 Test: 0
Future Date Test: 0

In [185]:
def get_report(report_type,start_date,end_date):
    report_type=report_type.lower().strip()

    try:
        start=datetime.strptime(start_date,"%Y-%m-%d")
        end=datetime.strptime(end_date,"%Y-%m-%d")
    except ValueError:
        print("Invalid date. Use YYYY-MM-DD.")
        return

    if end<start:
        print("End date cannot be before start date.")
        return

    days=(end-start).days+1

    if report_type=="daily":
        prev_end=start-timedelta(days=1)
        prev_start=prev_end
    elif report_type in ["weekly","monthly"]:
        prev_end=start-timedelta(days=1)
        prev_start=prev_end-timedelta(days=days-1)
    else:
        print("Invalid report type. Use daily, weekly or monthly.")
        return

    conn=sqlite3.connect(DB)

    query="""
    SELECT
        COUNT(DISTINCT o.order_id),
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2),
        COUNT(DISTINCT o.customer_id)
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    """

    current=conn.execute(
        query,
        (start_date,end_date)
    ).fetchone()

    previous=conn.execute(
        query,
        (
            prev_start.strftime("%Y-%m-%d"),
            prev_end.strftime("%Y-%m-%d")
        )
    ).fetchone()

    product_query="""
    SELECT
        p.product_name,
        ROUND(SUM(
            oi.quantity*oi.unit_price*
            (1-oi.discount_percent/100.0)
        ),2) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id=oi.order_id
    JOIN products p
        ON oi.product_id=p.product_id
    WHERE date(o.order_date) BETWEEN date(?) AND date(?)
    GROUP BY p.product_id,p.product_name
    ORDER BY revenue DESC
    LIMIT 3
    """

    products=conn.execute(
        product_query,
        (start_date,end_date)
    ).fetchall()

    conn.close()

    orders=current[0] or 0
    revenue=current[1] or 0
    customers=current[2] or 0
    previous_revenue=previous[1] or 0

    if previous_revenue!=0:
        change=(revenue-previous_revenue)/previous_revenue*100
    else:
        change=None

    print("\n========== E-COMMERCE REPORT ==========")
    print("Report Type:",report_type)
    print("Date Range:",start_date,"to",end_date)
    print("Total Orders:",orders)
    print("Revenue:",f"₹{revenue:,.2f}")
    print("Unique Customers:",customers)

    if change is None:
        print("Revenue Change: N/A")
    else:
        print("Revenue Change:",f"{change:.2f}%")

    print("\nTop 3 Products:")

    for i,(name,product_revenue) in enumerate(products,1):
        print(f"{i}. {name} - ₹{product_revenue:,.2f}")

    report_file=OUTPUT+r"\cli_report.txt"

    with open(report_file,"w",encoding="utf-8") as f:
        f.write("========== E-COMMERCE REPORT ==========\n")
        f.write(f"Report Type: {report_type}\n")
        f.write(f"Date Range: {start_date} to {end_date}\n")
        f.write(f"Total Orders: {orders}\n")
        f.write(f"Revenue: ₹{revenue:,.2f}\n")
        f.write(f"Unique Customers: {customers}\n")
        f.write(f"Revenue Change: {'N/A' if change is None else f'{change:.2f}%'}\n\n")
        f.write("Top 3 Products:\n")

        for i,(name,product_revenue) in enumerate(products,1):
            f.write(f"{i}. {name} - ₹{product_revenue:,.2f}\n")

    print("\n✅ Report saved to output/cli_report.txt")

In [186]:
test_invalid_order_id()
test_discount()
test_zero_quantity()
test_future_dates()

Invalid Order ID Test: 0
Discount > 100 Test: 0
Quantity = 0 Test: 0
Future Date Test: 0

In [187]:
if __name__=="__main__":
    report_type=input("Enter report type (daily/weekly/monthly): ").lower().strip()
    start_date=input("Enter start date (YYYY-MM-DD): ").strip()
    end_date=input("Enter end date (YYYY-MM-DD): ").strip()
    get_report(report_type,start_date,end_date)
    print("\n========== EDGE CASE TESTS ==========")
    test_invalid_order_id()
    test_discount()
    test_zero_quantity()
    test_future_dates()

Enter report type (daily/weekly/monthly):  monthly
Enter start date (YYYY-MM-DD):  2025-01-01
Enter end date (YYYY-MM-DD):  2025-01-31

========== E-COMMERCE REPORT ==========
Report Type: monthly
Date Range: 2025-01-01 to 2025-01-31
Total Orders: 18
Revenue: ₹383,252.71
Unique Customers: 18
Revenue Change: -26.41%

Top 3 Products:
1. Novel Score - ₹29,920.23
2. Novel Huge - ₹25,860.00
3. Monitor Sign - ₹25,552.62

✅ Report saved to output/cli_report.txt

========== EDGE CASE TESTS ==========
Invalid Order ID Test: 0
Discount > 100 Test: 0
Quantity = 0 Test: 0
Future Date Test: 0

In [188]:
import os

project=r"C:\Users\SUBHA PRAYASH\Desktop\CEI\DataEngineering003\WEEK_8_Ecommerce_Project_CEI"

for root,dirs,files in os.walk(project):
    level=root.replace(project,"").count(os.sep)
    indent="    "*level
    print(indent+os.path.basename(root)+"/")
    for file in files:
        print(indent+"    "+file)

WEEK_8_Ecommerce_Project_CEI/
    ecommerce.db
    Data/
        Cleaned/
            cleaning_report.csv
            customers_clean.csv
            orders_clean.csv
            order_items_clean.csv
            products_clean.csv
        Raw/
            customers.csv
            orders.csv
            order_items.csv
            products.csv
    Notebook/
        Final_Ecommerce_Project.ipynb
    Outputs/
        cli_report.txt
        cohort_retention.csv
        customers_no_delivery.csv
        customer_category_shift.csv
        customer_cumulative_revenue.csv
        customer_order_gaps.csv
        customer_quartiles.csv
        frequently_bought_together.csv
        monthly_customer_segments.csv
        monthly_orders.csv
        products_more_returns.csv
        product_ranking.csv
        return_rate_by_category.csv
        revenue_by_category.csv
        running_revenue_by_region.csv
        top_10_customers.csv
        year_over_year_revenue.csv
    Screenshots/
    SQL/
        Aggregations.sql
        Cohort_Analysis.sql
        Schema.sql
        Window_Functions.sql